before_script:
  - apt-get update -y
  - apt-get install -y build-essential python valgrind
  - python ci/install_cmake.py
  - export PATH=`pwd`/ci/build/cmake/bin:${PATH}

default:
  script:
    - ctest -VV -S CTestRun.cmake